name: Build and Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ "8.0.282+8", "11.0.4", "17.0" ]

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          # https://github.com/diffplug/spotless/issues/1242
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "zulu"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download or get from cache Sudachi dictionary
        id: download-and-cache-sudachi-dictionary
        uses: ./.github/actions/download-and-cache-sudachi-dictionary

      - name: Build
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew clean test

      - name: Run integration tests
        run: ./gradlew clean integrationTest

      - name: Run functional tests
        run: ./gradlew clean functionalTest

