name: Build and Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ "8.0.392+8", "11.0.21+9", "17.0.9+9", "21.0.2+13" ]

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          # https://github.com/diffplug/spotless/issues/1242
          fetch-depth: 0

      - name: Set up Azul Zulu OpenJDK Using Matrix
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "zulu"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download or get from cache Sudachi dictionary
        id: download-and-cache-sudachi-dictionary
        uses: ./.github/actions/download-and-cache-sudachi-dictionary

      - name: Build
        run: ./gradlew -PciRun build

      - name: Run unit tests
        run: ./gradlew -PciRun clean test

      - name: Run integration tests utilizing Tokenizer/Analyzer and imported Lucene Kuromoji tests
        run: ./gradlew -PciRun clean integrationTest

      - name: Run functional tests utilizing Lucene
        run: ./gradlew -PciRun clean functionalTest

      - name: Run end-to-end tests utilizing a Solr instance
        run: ./gradlew -PciRun clean endToEndTest

